version: '3'

services:
    postgresql:
        image: postgres
        container_name: postgres-shorten
        volumes:
            - ./postgresql:/var/lib/postgresql/data
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=shorten
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root

